### ISSUE TITLE
无法读取本地

### ISSUE THREAD

**Issue by st12138** [soonio/swagger-ui#1]
错误如下
![image](https://user-images.githubusercontent.com/44764311/221942478-7f5a5a7c-3a9c-4e68-b0c6-e0fa26db47c7.png)

**Comment by soonio** [comment]
你这个使用方式不对。你在本地打开，当然打不开了～

**Comment by st12138** [comment]
哈哈哈，解决了，没想到作者邮件答复，谢谢了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月8日 22:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [soonio/swagger-ui] 无法读取本地 (Issue #1)


你这个使用方式不对。你在本地打开，当然打不开了～

―
